[project]
name = "torch-opencl"
version = "0.1.0"
description = "A Python extension that integrates PyTorch with OpenCL, enabling GPU acceleration via the OpenCL API."
readme = "README.md"
authors = [{ name = "izzalDev", email = "rizal.fadlullah@gmail.com" }]
requires-python = ">=3.10"
dependencies = ["numpy<2.4", "torch>=2.11"]

[tool.scikit-build]
minimum-version = "build-system.requires"
build-dir = "build"
wheel.exclude = ["torch_opencl/csrc"]  # exclude C++ sources

[tool.uv]
cache-keys = [
	{ file = "pyproject.toml" },
	{ file = "csrc/**/*" },
	{ file = "torch_opencl/csrc/**/*" },
	{ file = "CMakeLists.txt" },
]

[tool.uv.sources]
torch = [{ index = "pytorch-cpu", marker = "sys_platform == 'linux'" }]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[build-system]
requires = ["scikit-build-core>=0.12", "nanobind>=2.12.0", "torch>=2.11", "numpy"]
build-backend = "scikit_build_core.build"

[dependency-groups]
dev = [
	"nanobind>=2.12.0",
	"ninja",
	"pre-commit>=4.6.0",
	"pyopencl>=2026.1.2",
	"pytest>=9.0",
	"scikit-build-core>=0.12",
]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "N",   # pep8-naming
]
ignore = [
    "E501", # line too long (handled by formatter)
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
