"""torch_opencl C extension module for PyTorch OpenCL backend."""



def is_in_bad_fork() -> bool: ...

def init() -> None: ...

def get_device_count() -> int: ...

def get_device() -> int: ...

def set_device(arg: int, /) -> None: ...

def exchange_device(arg: int, /) -> int: ...

def maybe_exchange_device(arg: int, /) -> int: ...
